[package]
name = "pcisph_rs"
version = "0.1.0"
edition = "2018"

[dependencies]
glium = "*"
glam = "*"
cgmath = "*"
rand = "*"
rayon = "*"
kdbush = "0.2.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false

[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
